name: yneko
description: Windows-first Flutter + Rust anime desktop application.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_rust_bridge: ^2.11.1
  flutter_svg: ^2.3.0
  media_kit: ^1.2.6
  media_kit_video: ^1.3.1
  media_kit_libs_windows_video: ^1.0.11
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/Yneko/
    - assets/icons/rail/
    - assets/illustrations/
    - assets/player-icons/
  fonts:
    - family: MiSansYneko
      fonts:
        - asset: assets/fonts/misans/MiSansYneko-Regular.ttf
          weight: 400
        - asset: assets/fonts/misans/MiSansYneko-Semibold.ttf
          weight: 600
        - asset: assets/fonts/misans/MiSansYneko-Bold.ttf
          weight: 700
        - asset: assets/fonts/misans/MiSansYneko-Bold.ttf
          weight: 800
