[package]
name = "yneko-api"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
reqwest.workspace = true
serde.workspace = true
tokio.workspace = true
yneko-core = { path = "../yneko-core" }
yneko-metadata = { path = "../yneko-metadata" }
yneko-source-rules = { path = "../yneko-source-rules" }
yneko-storage = { path = "../yneko-storage" }

[lints.rust]
unsafe_code = "allow"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
unwrap_used = "allow"
